project:
  type: website
  output-dir: docs

website:
  title: "jozielsc"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: Sobre


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



